### ISSUE TITLE
gagal checkout

### ISSUE THREAD

**Issue by khmuhtad1n** [bro-11/flasher#1]
![Screen Shot 2021-05-27 at 14 11 44](https://user-images.githubusercontent.com/23192230/119781738-8e623d80-bef5-11eb-97d5-c5ff15fe02e3.png)

**Comment by bro-11** [comment]
bisa kasih full error nya?

**Comment by qiwiled** [comment]
checkout di termux berhasil pas dicek di aplikasi shopee, ternyata belum tercheckout masih stay di keranjang
