### ISSUE TITLE
Ter - Checkout ( Namun Terbaca Harga Normal )

### ISSUE THREAD

**Issue by 0x0n1** [bro-11/flasher#15]
![Screenshot_256](https://user-images.githubusercontent.com/85106767/120913246-de908b00-c6bf-11eb-80ac-cacd9a8bd41b.png)

Saya Nyoba Pake 3 Akun Gan 
1 Saya Taroh Di VPS 
2 Di PC Pribadi

Yg 2 Akun Ter Checkout ( Di VPS & Di PC Pribadi Namun Terbacanya Harga Normal Bukan Harga Flashsale Seribu ) Yang 1 Gagal Checkout Mungkin Dikarenakan Saldo Shopeepay Nya Tidak Mencukupi. Hal Ini Juga Saya Alami Bulan Lalu Ketika Flashale. Mungkin Agan Bisa Bantu / Bikin Fitur Seperti Auto Refresh Di Detik-Detik Terakhir / 1 Menit Terakhir Sebelum Flashsale Agar Harganya Ke Refresh.
 
Terimakasih Banyak

**Comment by bro-11** [comment]
tadi malem ane ganti metodenya dari sleep manual ke auto refresh, sampe status flash sale nggak kosong baru itemnya di checkout.
mungkin bisa coba di `pull` lagi reponya, siapa tau work

**Comment by 0x0n1** [comment]
Oke Terimakasih Banyak Gan Udah Mau Share Botnya :D, Mantab Bot Nya. Sukses Terus Ya Gan

**Comment by 434fajar434** [comment]
@0x0n1 rdp speknya ram dan cpu berapa mas?

**Comment by 0x0n1** [comment]
> @0x0n1 rdp speknya ram dan cpu berapa mas?

Untuk vps nya os nya saya pake ubuntu mas, ram 2 gb 1 core, karena saya pikir kalo pake windows spek segitu kurang cukup, tapi kalo ubuntu menurut saya harusnya udah cukup mas
