### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by Alpha-Iso** [bro-11/flasher#2]
loginnya engga bisa bang, selalu muncul notifikasi "login error"

![login error](https://user-images.githubusercontent.com/84896824/119782647-a38b9c00-bef6-11eb-9d62-82aead5e7ac5.png)

**Comment by arisawali2014** [comment]
kayaknya error karna User-agent dibagian login.

**Comment by bro-11** [comment]
> kayaknya error karna User-agent dibagian login.

ya betul bang, tadi saya ganti tapi nggak saya test

**Comment by Alpha-Iso** [comment]
siap, udah bisa bang
